package com.bytepath.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Server-only adapter for a private Supabase Storage bucket. */
@Service
public class SupabaseStorageService {
    private static final Logger log = LoggerFactory.getLogger(SupabaseStorageService.class);
    private final HttpClient http = HttpClient.newBuilder()
        .connectTimeout(Duration.ofSeconds(20)).build();
    private final String baseUrl;
    private final String serviceRoleKey;
    private final String bucket;
    private final ObjectMapper objectMapper;

    public SupabaseStorageService(
            @Value("${supabase.url:}") String url,
            @Value("${supabase.service-role-key:}") String serviceRoleKey,
            @Value("${supabase.bucket-name:bytepath-resources}") String bucket,
            ObjectMapper objectMapper) {
        this.baseUrl = trimTrailingSlash(url) + "/storage/v1";
        this.serviceRoleKey = serviceRoleKey == null ? "" : serviceRoleKey.trim();
        this.bucket = bucket == null ? "" : bucket.trim();
        this.objectMapper = objectMapper;
    }

    public boolean isConfigured() {
        return !baseUrl.startsWith("/storage") && !baseUrl.equals("/storage/v1")
            && !serviceRoleKey.isBlank() && !bucket.isBlank();
    }

    public void upload(String objectKey, MultipartFile file, String contentType) {
        requireConfigured();
        try {
            request("PUT", objectUrl(objectKey), contentType,
                file.getBytes(), "x-upsert", "false");
        } catch (IOException ex) {
            throw new IllegalStateException("Could not read the uploaded file.", ex);
        }
    }

    public StorageObjectMetadata head(String objectKey) {
        requireConfigured();
        HttpResponse<byte[]> response = send("GET", signedObjectUrl(objectKey), null, null, null, null);
        ensureSuccess(response, "The uploaded object could not be found in storage.");
        long length = response.body().length;
        return new StorageObjectMetadata(length);
    }

    public byte[] getObjectBytes(String objectKey) {
        requireConfigured();
        HttpResponse<byte[]> response = send("GET", signedObjectUrl(objectKey), null, null, null, null);
        ensureSuccess(response, "The protected resource could not be read from storage.");
        return response.body();
    }

    public void delete(String objectKey) {
        requireConfigured();
        String payload = "{\"prefixes\":[\"" + objectKey.replace("\\", "\\\\").replace("\"", "\\\"") + "\"]}";
        request("POST", URI.create(baseUrl + "/object/" + bucket),
            "application/json", payload.getBytes(StandardCharsets.UTF_8), null, null);
    }

    private HttpResponse<byte[]> request(String method, URI uri, String contentType,
                                         byte[] body, String extraHeader, String extraValue) {
        HttpResponse<byte[]> response = send(method, uri, contentType, body, extraHeader, extraValue);
        ensureSuccess(response, "Supabase Storage rejected the request.");
        return response;
    }

    private HttpResponse<byte[]> send(String method, URI uri, String contentType,
                                      byte[] body, String extraHeader, String extraValue) {
        try {
            HttpRequest.BodyPublisher publisher = body == null
                ? HttpRequest.BodyPublishers.noBody()
                : HttpRequest.BodyPublishers.ofByteArray(body);
            HttpRequest.Builder builder = HttpRequest.newBuilder(uri)
                .timeout(Duration.ofSeconds(120))
                .header("Authorization", "Bearer " + serviceRoleKey)
                .header("apikey", serviceRoleKey)
                .method(method, publisher);
            if (contentType != null && !contentType.isBlank()) builder.header("Content-Type", contentType);
            if (extraHeader != null) builder.header(extraHeader, extraValue);
            return http.send(builder.build(), HttpResponse.BodyHandlers.ofByteArray());
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Storage request was interrupted.", ex);
        } catch (IOException ex) {
            throw new IllegalStateException("Could not connect to Supabase Storage.", ex);
        }
    }

    private URI objectUrl(String objectKey) {
        // Object keys are generated by the backend and contain only safe path characters.
        return URI.create(baseUrl + "/object/" + bucket + "/" + objectKey);
    }

    private URI authenticatedObjectUrl(String objectKey) {
        return URI.create(baseUrl + "/object/authenticated/" + bucket + "/" + objectKey);
    }

    private URI signedObjectUrl(String objectKey) {
        try {
            String payload = objectMapper.writeValueAsString(java.util.Map.of("expiresIn", 120));
            HttpResponse<byte[]> response = request("POST",
                URI.create(baseUrl + "/object/sign/" + bucket + "/" + objectKey),
                "application/json", payload.getBytes(java.nio.charset.StandardCharsets.UTF_8), null, null);
            String signedPath = objectMapper.readTree(response.body()).path("signedURL").asText();
            if (signedPath.isBlank()) throw new IllegalStateException("Supabase did not return a signed URL.");
            return URI.create(signedPath.startsWith("http") ? signedPath : baseUrl + signedPath);
        } catch (Exception ex) {
            if (ex instanceof IllegalStateException state) throw state;
            throw new IllegalStateException("Could not create a Supabase signed URL.", ex);
        }
    }

    private void ensureSuccess(HttpResponse<byte[]> response, String message) {
        if (response.statusCode() < 200 || response.statusCode() >= 300) {
            String body = new String(response.body(), StandardCharsets.UTF_8);
            log.error("Supabase Storage request failed: status={}, response={}", response.statusCode(), body);
            throw new IllegalStateException(message + " (HTTP " + response.statusCode() + ")");
        }
    }

    private void requireConfigured() {
        if (!isConfigured()) throw new IllegalStateException("Supabase Storage is not configured on the backend.");
    }

    private static String trimTrailingSlash(String value) {
        if (value == null || value.isBlank()) return "";
        return value.trim().replaceAll("/+$", "");
    }

    public record StorageObjectMetadata(long contentLength) {}
}
